### ISSUE TITLE
JavaScript "must be on" message

### ISSUE THREAD

**Issue by necolas** [richardshepherd/TwentyTenFive#1]
In header.php there is markup in a noscript element that says "you need to turn JavaScript on to use this site". The url it points to 404's - http://turnjavascripton.com

But there should be no JavaScript requirement to view content on a blog. It should display content to users with JS off, without a "warning" or prompting them to turn it on.

**Comment by richardshepherd** [comment]
I've removed that placeholder URL to avoid confusion, and amended the message.

TwentyTen Five relies on JavaScript for IE6-IE8 users (because it's built on HTML5) and so these users need a warning as the site won't format correctly.

If you want to support users with JS disabled then TwentyTen Five isn't the theme for you!

**Comment by necolas** [comment]
Hi Richard,

I'm fully aware of the need for the JS shim for IE<9 users. However, the message will display to users of any browser with JS disabled, even though users of modern browsers will not require JS. i.e., the message is misleading when presented to, for example, users of the Firefox/Chrome NoScript extension.

**Comment by richardshepherd** [comment]
That's a great point, necolas. I've wrapped the noscript message in a lte IE8 conditional.
